[versions]
# android versions
compileSdk = "34"
targetSdk = "34"
minSdk = "26"
versionCode = "1"
versionName = "0.0.1"
# plugin versions
android-plugin = "8.1.0"
kotlin-plugin = "1.7.10"
kotlin-kapt = "1.9.10"
kotlin-parcelize = "1.9.10"
hilt = "2.42"
google-services = "4.3.13"
navigation-safe-args = "2.5.3"
android-tools = "7.3.0"
firebase-crashlytics-gradle = "2.8.1"
google-gms = "4.3.8"
crashlytics = "2.8.1"
# library versions
kotlinStdLib = "1.7.10"
bp-media-picker = "2.0.1"
bp-media-viewer = "1.1.3"
bp-common = "1.3.0"
bp-permission-provider = "1.0.0"
bp-notification = "1.0.1"
bp-push-notif = "1.0.1"
bp-report = "2.2.0"
bp-intro = "2.0.8"
steps-indicator = "0.0.3"
bp-notification-list = "1.0.1"
androidx = "1.9.0"
androidx-appcompat = "1.5.0"
androidx-constraint = "2.1.4"
androidx-coordinator = "1.2.0"
androidx-recyclerview = "1.3.1"
androidx-activity = "1.7.0"
androidx-fragment = "1.5.6"
androidx-navigation-fragment = "2.5.3"
androidx-junit = "1.1.3"
androidx-espresso = "3.4.0"
androidx-test-rules = "1.3.0"
androidx-test-runner = "1.3.0"
androidx-browser = "1.5.0"
androidx-paging-runtime = "3.1.1"
androidx-lifecycle-compiler = "2.6.2"
androidx-lifecycle-common = "2.6.2"
androidx-livedata = "2.6.1"
androidx-viewmodel = "2.6.1"
androidx-runtime = "2.3.1"
androidx-activity-compose = "1.3.1"
androidx-preference = "1.2.1"
androidx-viewpager = "1.0.0"
androidx-legacy-support = "1.0.0"
material = "1.6.1"
firebase = "21.3.0"
firebase-bom = "32.1.0"
mixpanel = "6.5.2"
segment = "1.10.6"
timber = "5.0.1"
circle-imageview = "3.1.0"
timeago = "4.0.3"
glide = "4.12.0"
facebook-shimmer = "0.5.0"
facebook-sdk = "16.0.0"
facebook-stetho = "1.6.0"
runtime-permission = "0.10.2"
permission-dispatcher = "1.1.4"
ucrop = "2.2.7"
coroutines = "1.6.4"
flowbinding = "1.2.0"
databinding = "3.1.4"
room = "2.4.3"
retrofit = "2.9.0"
okhttp = "5.0.0-alpha.11"
zelory-compressor = "3.0.1"
light-compressor = "1.2.3"
gson = "2.10"
libphonenumber = "8.13.18"
google-play-services-auth = "19.0.0"
google-play-services-location = "18.0.0"
google-play-services-maps = "17.0.1"
security-crypto = "1.1.0-alpha06"
sql-cipher = "4.4.3"
sql-lite = "2.3.1"
country-code = "2.7.0"
navigation = "2.5.3"
view-pager2 = "1.0.0"
core-ktx = "1.10.1"
touch-imageview = "3.5"
compose = "1.3.0-beta03"
rx-kotlin = "2.4.0"
exoplayer = "2.17.1"
otalias-zoomlayout = "1.9.0"
kohii = "1.4.0.2017001"
glassfish = "10.0-b28"
chucker = "3.5.2"
shake-detector = "1.0.3"
stripe = "16.3.0"
preference = "1.2.1"
paging = "2.4.3"
matisse = "0.5.3-beta3"
data-transport-runtime = "3.1.8"
sdp = "1.1.0"
# test library versions
junit = "4.13.2"
mockito = "3.11.0"
arch = "2.2.0"
mockk = "1.12.4"
google-truth = "1.1.3"
espresso-contrib = "3.0.2"
billingClient = "5.2.0"
ablyAndroid = "1.2.0"
androidx-swipe-refresher = "1.1.0"
country-picker = "2.0.4"
chatkit = "0.4.1"
[plugins]
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-plugin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
android = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
navigation = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
[libraries]
# Kotlin
kotlinStdLib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlinStdLib" }

# Build Libs
android-tools = { group = "com.android.tools.build", name = "gradle", version.ref = "android-tools" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlinStdLib" }
firebase-crashlytics-gradle = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }
google-gms = { group = "com.google.gms", name = "google-services", version.ref = "google-gms" }
navigation-safe-args = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "navigation-safe-args" }
hilt-gradle = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }

# Baseplate
bp-media-picker = { module = "com.appetiser.mediapicker:mediapicker", version.ref = "bp-media-picker" }
bp-media-viewer = { module = "com.appetiser.baseplate:mediaviewer", version.ref = "bp-media-viewer" }
bp-common = { module = "com.appetiser.common:common", version.ref = "bp-common" }
bp-permission-provider = { module = "com.appetiser.permissionprovider:permissionprovider", version.ref = "bp-permission-provider" }
bp-notification = { module = "com.appetiser.notification:notification", version.ref = "bp-notification" }
bp-notification-core = { module = "com.appetiser.notification:notificationCore", version.ref = "bp-notification" }
bp-push-notif = { module = "com.appetiser.pushNotificationsCore:pushNotificationsCore", version.ref = "bp-push-notif" }
bp-report = { module = "com.appetiser.report:report", version.ref = "bp-report" }
bp-report-core = { module = "com.appetiser.report:reportcore", version.ref = "bp-report" }
bp-intro = { module = "com.appetiser.onboarding:onboarding", version.ref = "bp-intro" }
bp-notification-list = { module = "com.appetiser.notification:notification", version.ref = "bp-notification-list" }

# Steps Indicator
steps-indicator = { module = "au.com.appetiser.baseplate:stepsindicatorview", version.ref = "steps-indicator" }


# AndroidX
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx" }
androidx-support-design = { module = "com.google.android.material:material", version.ref = "material" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-constraint = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-constraint" }
androidx-coordinator = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "androidx-coordinator" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-activity = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation-fragment" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx.test-runner" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging-runtime" }
androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "androidx-lifecycle-compiler" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle-common" }
androidx-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-livedata" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-viewmodel" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-runtime" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-preference = { module = "androidx.preference:preference-ktx", version.ref = "androidx-preference" }
androidx-viewpager = { module = "androidx.viewpager2:viewpager2", version.ref = "androidx-viewpager" }
androidx-swipe-refresher = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "androidx-swipe-refresher" }
androidx-legacy-support = { module = "androidx.legacy:legacy-support-v4", version.ref = "androidx-legacy-support"}

# Hilt
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

# Material
material = { module = "com.google.android.material:material", version.ref = "material" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-bom-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "firebase" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }

# Mixpanel
mixpanel = { module = "com.mixpanel.android:mixpanel-android", version.ref = "mixpanel" }

# Segment
segment = { module = "com.segment.analytics.kotlin:android", version.ref = "segment" }

# Timber
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Circle image view
circle-imageview = { module = "de.hdodenhof:circleimageview", version.ref = "circle-imageview" }

# JUnit
junit = { module = "junit:junit", version.ref = "junit" }

# Timeago
timeago = { module = "com.github.marlonlom:timeago", version.ref = "timeago" }

# Glide
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

# Facebook
facebook-shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "facebook-shimmer" }
facebook-sdk = { module = "com.facebook.android:facebook-login", version.ref = "facebook-sdk" }
facebook-stetho = { module = "com.facebook.stetho:stetho", version.ref = "facebook-stetho" }

# Runtime permission
runtime-permission = { module = "com.github.tbruyelle:rxpermissions", version.ref = "runtime-permission" }

# Permission dispatcher
permission-dispatcher = { module = "com.github.permissions-dispatcher:ktx", version.ref = "permission-dispatcher" }

# UCrop
ucrop = { module = "com.github.yalantis:ucrop", version.ref = "ucrop" }

# Coroutines
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-core-testing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "coroutines" }

# Flow
flowbinding-android = { module = "io.github.reactivecircus.flowbinding:flowbinding-android", version.ref = "flowbinding" }
flowbinding-core = { module = "io.github.reactivecircus.flowbinding:flowbinding-core", version.ref = "flowbinding" }
flowbinding-appcompat = { module = "io.github.reactivecircus.flowbinding:flowbinding-appcompat", version.ref = "flowbinding" }

# Databinding
databinding-compiler = { module = "com.android.databinding:compiler", version.ref = "databinding" }

# Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

# Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }

# OkHttp
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# Zelory compressor
zelory-compressor = { module = "id.zelory:compressor", version.ref = "zelory-compressor" }

# Light compressor
light-compressor = { module = "com.github.AbedElazizShe:LightCompressor", version.ref = "light-compressor" }

# Exoplayer
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer" }
exoplayer-dash = { module = "com.google.android.exoplayer:exoplayer-dash", version.ref = "exoplayer" }
exoplayer-hls = { module = "com.google.android.exoplayer:exoplayer-hls", version.ref = "exoplayer" }

# Otalias zoomlayout
otalias-zoomlayout = { module = "com.otaliastudios:zoomlayout", version.ref = "otalias-zoomlayout" }

# Kohii
kohii = { module = "im.ene.kohii:kohii-core", version.ref = "kohii" }
kohii-exoplayer = { module = "im.ene.kohii:kohii-exoplayer", version.ref = "kohii" }

# Mockito
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }

# Arch
arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "arch" }

# Gson
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# Mockk
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-jvm = { module = "io.mockk:mockk-agent-jvm", version.ref = "mockk" }

# Google Truth
google-truth = { module = "com.google.truth:truth", version.ref = "google-truth" }

# Espresso
espresso-contrib = { module = "com.android.support.test.espresso:espresso-contrib", version.ref = "espresso-contrib" }

# Libphonenumber
lib-phone-number = { module = "com.googlecode.libphonenumber:libphonenumber", version.ref = "libphonenumber" }

# Google Play Services
google-play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "google-play-services-auth" }
google-play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "google-play-services-location" }
google-play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "google-play-services-maps" }

# Security Crypto
security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }

# SQL Cipher
sql-cipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "sql-cipher" }

# SQL Lite
sql-lite = { module = "androidx.sqlite:sqlite", version.ref = "sql-lite" }

# Country Code
country-code = { module = "com.hbb20:ccp", version.ref = "country-code" }

# Navigation Fragment UI
navigation-fragment-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }

# View Pager 2
view-pager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "view-pager2" }

# Touch Image View
touch-imageview = { module = "com.github.MikeOrtiz:TouchImageView", version.ref = "touch-imageview" }

# Compose
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }

# RxKotlin
rx-kotlin = { module = "io.reactivex.rxjava2:rxkotlin", version.ref = "rx-kotlin" }

# Glass fish
glassfish = { module = "org.glassfish:javax.annotation", version.ref = "glassfish" }

# Chucker
chucker = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-noop = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }

# Shake detector
shake-detector = { module = "com.squareup:seismic", version.ref = "shake-detector" }

# Stripe
stripe = { module = "com.stripe:stripe-android", version.ref = "stripe" }

# Preference
preference = { module = "androidx.preference:preference-ktx", version.ref = "preference" }

# Paging
paging = { module = "androidx.room:room-paging", version.ref = "paging" }

# Billing Client
billingClient = { module = "com.android.billingclient:billing-ktx", version.ref = "billingClient" }

# ChatKit
chatKit = { module = "com.github.stfalcon-studio:ChatKit", version.ref = "chatkit" }

# Ably-Android
ably = { module = "io.ably:ably-android", version.ref = "ablyAndroid" }

# Matisse
matisse = { module = "com.zhihu.android:matisse", version.ref = "matisse" }

# Data Transport Runtime
data-transport-runtime = { module = "com.google.android.datatransport:transport-runtime", version.ref = "data-transport-runtime" }

# Country Picker
country-picker = { module = "com.github.mukeshsolanki:country-picker-android", version.ref = "country-picker" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version = "2.7.5" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version = "2.7.5" }

# DP to all Densities
intuit-sdp = { module = "com.intuit.sdp:sdp-android", version.ref = "sdp"}

intuit-ssp = { module = "com.intuit.sdp:ssp-android", version.ref = "sdp"}
