[versions]
    androidx-test = "1.4.0"
    androidx-junit = "1.1.3"
    androidx-arch-testing = "2.1.0"
    androidx-espresso = "3.4.0"
    androidx-test-rules = "1.3.0"
    androidx-test-runner = "1.3.0"
    espresso-contrib = "3.0.2"
    junit = "4.13.2"
    google-truth = "1.1.3"
    mockk = "1.12.4"
    coroutines-test = "1.7.3"
    compose = "1.3.0-beta03"
    androidx-fragment-testing = "1.2.5"

[libraries]
    # Androidx
    androidx-test = { module = "androidx.test:core", version.ref = "androidx-test" }
    androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
    androidx-arch-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch-testing" }
    androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
    androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }
    androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
    androidx-fragment-testing = { module = "androidx.fragment:fragment-testing", version.ref = "androidx-fragment-testing"}

    # Espresso
    espresso-contrib = { module = "com.android.support.test.espresso:espresso-contrib", version.ref = "espresso-contrib" }

    # JUnit
    junit = { module = "junit:junit", version.ref = "junit" }

    # Google
    google-truth = { module = "com.google.truth:truth", version.ref = "google-truth" }

    # MockK
    mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
    mockk-jvm = { module = "io.mockk:mockk-agent-jvm", version.ref = "mockk" }

    # Coroutines
    coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-test" }

    # Compose
    compose-ui-junit = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
    compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }